openapi: 3.0.3
info:
  title: STD23087 - TD3
  version: '1.0.3'
servers:
  - url: https://localhost.std23087.com
paths:
  /meals:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
      responses:
        200:
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMeal'
        required: true
      responses:
        201:
          description: Created meal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Meal'
        required: true
      responses:
        200:
          description: Updated meal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
    delete:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealIdentifier'
        required: true
      responses:
        200:
          description: List of deleted meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
  /meals/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Meal by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
        404:
          description: Meal not found

components:
  schemas:
    Meal:
      allOf:
        - $ref: '#/components/schemas/MealIdentifier'
        - $ref: '#/components/schemas/CreateMeal'
    MealIdentifier:
      type: object
      properties:
        id:
          type: string
    CreateMeal:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: decimal
      required:
        - name
        - price
